### ISSUE TITLE
Invalid remote Gitlab url: https://***

### ISSUE THREAD

**Issue by andrisp** [bsideup/IDEA-GitLab-Integration#21]
Installed plugin from the jetbrains plugin repository.
When tried to use the "Open in Gitlab", got this exception:
[gitlab_exc.txt](https://github.com/bsideup/IDEA-GitLab-Integration/files/323161/gitlab_exc.txt)

**Comment by bsideup** [comment]
@andrisp it will not work if you use `git://` remotes. Right now only http/https is supported

**Comment by andrisp** [comment]
@bsideup I'm using https://.

**Comment by bsideup** [comment]
@andrisp can you post slightly less obfuscated exception?

**Comment by andrisp** [comment]
@bsideup the only thing I didnt include in the exception was the domain and the path from the URL because of the privacy reasons. As you see in the attached filed, the remote repo URL starts with `https://`. I was checking the source of the plugin, and have no idea why I'm getting the error, the code looks ok.

**Comment by mrh1997** [comment]
Same on my PC.
For quick reproducability I checked out a sample project (https://gitlab.com/tobyd/drone-boat.git) under PyCharm (2016.1; Windows) and clicked "Open on GitLab".

Then I get the following error: https://gist.github.com/mrh1997/ef1a22896205255adb84ab88b896f64f

**Comment by shurupov** [comment]
[The same](https://gist.github.com/shurupov/a27f8cb603c68256b9aec00db2c15931)
The repository is private

**Comment by aledoroshenko** [comment]
Same issue. Had repo with ssh link, used git set-url to switch to https one, but no luck, it says 'wrong url'.

**Comment by Gogowitsch** [comment]
I just ran into this with PhpStorm 2018.3.3.

The URL in first line of the following stack trace works fine when opened in a browser.

````
java.lang.IllegalStateException: Invalid remote Gitlab url: https://git04.quodata.de/qd_drupal_projects/qd_base_entity.git
	at ru.trylogic.idea.gitlab.integration.utils.GitlabUrlUtil.makeRepoUrlFromRemoteUrl(GitlabUrlUtil.java:36)
	at ru.trylogic.idea.gitlab.integration.actions.GitLabOpenInBrowserAction.makeUrlToOpen(GitLabOpenInBrowserAction.java:63)
	at ru.trylogic.idea.gitlab.integration.actions.RemoteSelectedAction.actionPerformed(GitLabOpenInBrowserAction.java:238)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
````

**Comment by pvalsecc** [comment]
The issue is this line of code: https://github.com/bsideup/IDEA-GitLab-Integration/blob/db5cae0d76cd70fae172bb9533bc0b6ec35c1672/src/ru/trylogic/idea/gitlab/integration/utils/GitlabUrlUtil.java#L31
If your username is not `git`, you are toast. Mine is `gitlab`.
